[package]
name = "libcraft-particles"
version = "0.1.0"
authors = ["Gijs de Jong <berichtaangijs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcraft-blocks = { path = "../blocks"}
libcraft-items = { path = "../items" }
ordinalizer = "0.1.0"